USE Metabase;

BEGIN TRAN;

DELETE
FROM SecondaryLanguage
WHERE Language = 'en';

DELETE
FROM MetaAdm
WHERE Value = 'ENG';

DROP TABLE IF EXISTS Attribute_Eng;
DROP TABLE IF EXISTS ColumnCode_Eng;
DROP TABLE IF EXISTS Contents_Eng;
DROP TABLE IF EXISTS Footnote_Eng;
DROP TABLE IF EXISTS GroupingLevel_Eng;
DROP TABLE IF EXISTS Grouping_Eng;
DROP TABLE IF EXISTS Link_Eng;
DROP TABLE IF EXISTS MainTable_Eng;
DROP TABLE IF EXISTS MenuSelection_Eng;
DROP TABLE IF EXISTS Organization_Eng;
DROP TABLE IF EXISTS SpecialCharacter_Eng;
DROP TABLE IF EXISTS SubTable_Eng;
DROP TABLE IF EXISTS TextCatalog_Eng;
DROP TABLE IF EXISTS TimeScale_Eng;
DROP TABLE IF EXISTS VSValue_Eng;
DROP TABLE IF EXISTS ValueGroup_Eng;
DROP TABLE IF EXISTS ValuePool_Eng;
DROP TABLE IF EXISTS ValueSet_Eng;
DROP TABLE IF EXISTS Value_Eng;
DROP TABLE IF EXISTS Variable_Eng;

COMMIT TRAN;